# Generated by Django 3.0.7 on 2020-06-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField(verbose_name='First name')),
                ('lastName', models.TextField(verbose_name='Last name')),
                ('institution', models.TextField(verbose_name='Institution')),
                ('reasonToAccess', models.TextField(verbose_name='Why do you need acces to database?')),
                ('email', models.EmailField(max_length=254, verbose_name='Email request user')),
            ],
        ),
    ]
