# Generated by Django 3.0.7 on 2020-07-12 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentcharacteristic',
            name='instrumentID',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to='data.Instrument', verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrumentmodel',
            name='instrumentID',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='data.Instrument', verbose_name=''),
            preserve_default=False,
        ),
    ]
