# Generated by Django 3.0.7 on 2020-07-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200712_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumentmodel',
            name='instrumentID',
        ),
        migrations.AddField(
            model_name='instrumentmodel',
            name='instrumentID',
            field=models.ManyToManyField(to='data.Instrument', verbose_name=''),
        ),
    ]
