# Generated by Django 3.0.7 on 2020-07-12 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200712_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentCharacteristicName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristicName', models.CharField(max_length=50, verbose_name='Characteristic of a instrument')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentCharacteristicValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristicsValue', models.CharField(max_length=50, verbose_name='Value of the Characteristic')),
                ('characteristicNameID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='data.InstrumentCharacteristicName', verbose_name='')),
                ('instrumentID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='data.Instrument', verbose_name='')),
            ],
        ),
        migrations.DeleteModel(
            name='InstrumentCharacteristic',
        ),
    ]
