# Generated by Django 3.0.7 on 2020-07-12 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20200712_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentcharacteristicvalue',
            name='characteristicNameID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='data.InstrumentCharacteristicName', verbose_name='Characteristic Name'),
        ),
        migrations.AlterField(
            model_name='instrumentcharacteristicvalue',
            name='instrumentID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='data.Instrument', verbose_name='Instrument'),
        ),
    ]
