# Generated by Django 3.0.7 on 2020-07-12 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20200712_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumentmodel',
            name='instrumentID',
        ),
        migrations.AddField(
            model_name='instrument',
            name='modelID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.InstrumentModel', verbose_name='Station Name'),
            preserve_default=False,
        ),
    ]
